const STATUSES = {
  NOT_SET: 'NOT_SET',
  POMO_RUNNING: 'POMO_RUNNING',
  POMO_PAUSED: 'POMO_PAUSED'
  // BREAK_RUNNING: 'BREAK_RUNNING',
  // POMO_COMPLETE: 'POMO_COMPLETE'
};

export default STATUSES;
